# Generated by Django 5.2.14 on 2026-05-27 12:01

import django.db.models.deletion
import django.utils.timezone
import ingest.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP (Fuel/Procurement Export)'), ('UTILITY', 'Utility Portal Export'), ('TRAVEL', 'Corporate Travel Export')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PARSED', 'Parsed'), ('PARTIAL', 'Partial (Some Errors)'), ('FAILED', 'Failed'), ('LOCKED', 'Locked for Audit')], default='CREATED', max_length=20)),
                ('input_file', models.FileField(blank=True, null=True, upload_to=ingest.models.upload_to_job)),
                ('received_rows', models.PositiveIntegerField(default=0)),
                ('parsed_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('suspicious_rows', models.PositiveIntegerField(default=0)),
                ('approved_rows', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.organization')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='ingest.ingestionsource')),
            ],
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('parsed', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PARSED', 'Parsed'), ('ERROR', 'Error')], max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingest.ingestionjob')),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FUEL', 'Fuel'), ('PROCUREMENT', 'Procurement'), ('ELECTRICITY', 'Electricity'), ('TRAVEL_FLIGHT', 'Travel: Flight'), ('TRAVEL_HOTEL', 'Travel: Hotel'), ('TRAVEL_GROUND', 'Travel: Ground')], max_length=30)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=20)),
                ('source_row_ref', models.CharField(blank=True, max_length=120)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('normalized_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('normalized_unit', models.CharField(blank=True, max_length=32)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('spend_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('spend_currency', models.CharField(blank=True, max_length=8)),
                ('traveler', models.CharField(blank=True, max_length=200)),
                ('origin', models.CharField(blank=True, max_length=16)),
                ('destination', models.CharField(blank=True, max_length=16)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('suspicious', models.BooleanField(default=False)),
                ('suspicious_reasons', models.JSONField(blank=True, default=list)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.facility')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingest.ingestionjob')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='core.organization')),
                ('raw_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.rawrecord')),
            ],
        ),
        migrations.CreateModel(
            name='RecordEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='ingest.normalizedrecord')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ingestionsource',
            constraint=models.UniqueConstraint(fields=('org', 'source_type', 'name'), name='uniq_source_per_org'),
        ),
        migrations.AddConstraint(
            model_name='rawrecord',
            constraint=models.UniqueConstraint(fields=('job', 'row_number'), name='uniq_raw_row_per_job'),
        ),
    ]
